name: diabetes_habits_app
description: App de hábitos para personas con diabetes.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  # Localización
  generate: true

  # Generación de traducciones
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_es.arb
    output-localization-file: app_localizations.dart
